language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "pip install setuptools==20.0"
    - "python setup.py install"
    - "pip install -r requirement/dev.txt"

# command to run tests
script:
    - "make lint"
    - "make test"
